#
# Autogenerated by Thrift Compiler (1.0.0-dev)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
require 5.6.0;
use strict;
use warnings;
use Thrift;

use rs::thrift::Types;

# HELPER FUNCTIONS AND STRUCTURES

package rs::thrift::HandleData_import_entities_args;
use base qw(Class::Accessor);
rs::thrift::HandleData_import_entities_args->mk_accessors( qw( entityJson ) );

sub new {
  my $classname = shift;
  my $self      = {};
  my $vals      = shift || {};
  $self->{entityJson} = undef;
  if (UNIVERSAL::isa($vals,'HASH')) {
    if (defined $vals->{entityJson}) {
      $self->{entityJson} = $vals->{entityJson};
    }
  }
  return bless ($self, $classname);
}

sub getName {
  return 'HandleData_import_entities_args';
}

sub read {
  my ($self, $input) = @_;
  my $xfer  = 0;
  my $fname;
  my $ftype = 0;
  my $fid   = 0;
  $xfer += $input->readStructBegin(\$fname);
  while (1) 
  {
    $xfer += $input->readFieldBegin(\$fname, \$ftype, \$fid);
    if ($ftype == TType::STOP) {
      last;
    }
    SWITCH: for($fid)
    {
      /^1$/ && do{      if ($ftype == TType::STRING) {
        $xfer += $input->readString(\$self->{entityJson});
      } else {
        $xfer += $input->skip($ftype);
      }
      last; };
        $xfer += $input->skip($ftype);
    }
    $xfer += $input->readFieldEnd();
  }
  $xfer += $input->readStructEnd();
  return $xfer;
}

sub write {
  my ($self, $output) = @_;
  my $xfer   = 0;
  $xfer += $output->writeStructBegin('HandleData_import_entities_args');
  if (defined $self->{entityJson}) {
    $xfer += $output->writeFieldBegin('entityJson', TType::STRING, 1);
    $xfer += $output->writeString($self->{entityJson});
    $xfer += $output->writeFieldEnd();
  }
  $xfer += $output->writeFieldStop();
  $xfer += $output->writeStructEnd();
  return $xfer;
}

package rs::thrift::HandleData_import_entities_result;
use base qw(Class::Accessor);
rs::thrift::HandleData_import_entities_result->mk_accessors( qw( success ) );

sub new {
  my $classname = shift;
  my $self      = {};
  my $vals      = shift || {};
  $self->{success} = undef;
  if (UNIVERSAL::isa($vals,'HASH')) {
    if (defined $vals->{success}) {
      $self->{success} = $vals->{success};
    }
  }
  return bless ($self, $classname);
}

sub getName {
  return 'HandleData_import_entities_result';
}

sub read {
  my ($self, $input) = @_;
  my $xfer  = 0;
  my $fname;
  my $ftype = 0;
  my $fid   = 0;
  $xfer += $input->readStructBegin(\$fname);
  while (1) 
  {
    $xfer += $input->readFieldBegin(\$fname, \$ftype, \$fid);
    if ($ftype == TType::STOP) {
      last;
    }
    SWITCH: for($fid)
    {
      /^0$/ && do{      if ($ftype == TType::STRING) {
        $xfer += $input->readString(\$self->{success});
      } else {
        $xfer += $input->skip($ftype);
      }
      last; };
        $xfer += $input->skip($ftype);
    }
    $xfer += $input->readFieldEnd();
  }
  $xfer += $input->readStructEnd();
  return $xfer;
}

sub write {
  my ($self, $output) = @_;
  my $xfer   = 0;
  $xfer += $output->writeStructBegin('HandleData_import_entities_result');
  if (defined $self->{success}) {
    $xfer += $output->writeFieldBegin('success', TType::STRING, 0);
    $xfer += $output->writeString($self->{success});
    $xfer += $output->writeFieldEnd();
  }
  $xfer += $output->writeFieldStop();
  $xfer += $output->writeStructEnd();
  return $xfer;
}

package rs::thrift::HandleData_add_entity_args;
use base qw(Class::Accessor);
rs::thrift::HandleData_add_entity_args->mk_accessors( qw( entityJson ) );

sub new {
  my $classname = shift;
  my $self      = {};
  my $vals      = shift || {};
  $self->{entityJson} = undef;
  if (UNIVERSAL::isa($vals,'HASH')) {
    if (defined $vals->{entityJson}) {
      $self->{entityJson} = $vals->{entityJson};
    }
  }
  return bless ($self, $classname);
}

sub getName {
  return 'HandleData_add_entity_args';
}

sub read {
  my ($self, $input) = @_;
  my $xfer  = 0;
  my $fname;
  my $ftype = 0;
  my $fid   = 0;
  $xfer += $input->readStructBegin(\$fname);
  while (1) 
  {
    $xfer += $input->readFieldBegin(\$fname, \$ftype, \$fid);
    if ($ftype == TType::STOP) {
      last;
    }
    SWITCH: for($fid)
    {
      /^1$/ && do{      if ($ftype == TType::STRING) {
        $xfer += $input->readString(\$self->{entityJson});
      } else {
        $xfer += $input->skip($ftype);
      }
      last; };
        $xfer += $input->skip($ftype);
    }
    $xfer += $input->readFieldEnd();
  }
  $xfer += $input->readStructEnd();
  return $xfer;
}

sub write {
  my ($self, $output) = @_;
  my $xfer   = 0;
  $xfer += $output->writeStructBegin('HandleData_add_entity_args');
  if (defined $self->{entityJson}) {
    $xfer += $output->writeFieldBegin('entityJson', TType::STRING, 1);
    $xfer += $output->writeString($self->{entityJson});
    $xfer += $output->writeFieldEnd();
  }
  $xfer += $output->writeFieldStop();
  $xfer += $output->writeStructEnd();
  return $xfer;
}

package rs::thrift::HandleData_add_entity_result;
use base qw(Class::Accessor);
rs::thrift::HandleData_add_entity_result->mk_accessors( qw( success ) );

sub new {
  my $classname = shift;
  my $self      = {};
  my $vals      = shift || {};
  $self->{success} = undef;
  if (UNIVERSAL::isa($vals,'HASH')) {
    if (defined $vals->{success}) {
      $self->{success} = $vals->{success};
    }
  }
  return bless ($self, $classname);
}

sub getName {
  return 'HandleData_add_entity_result';
}

sub read {
  my ($self, $input) = @_;
  my $xfer  = 0;
  my $fname;
  my $ftype = 0;
  my $fid   = 0;
  $xfer += $input->readStructBegin(\$fname);
  while (1) 
  {
    $xfer += $input->readFieldBegin(\$fname, \$ftype, \$fid);
    if ($ftype == TType::STOP) {
      last;
    }
    SWITCH: for($fid)
    {
      /^0$/ && do{      if ($ftype == TType::STRING) {
        $xfer += $input->readString(\$self->{success});
      } else {
        $xfer += $input->skip($ftype);
      }
      last; };
        $xfer += $input->skip($ftype);
    }
    $xfer += $input->readFieldEnd();
  }
  $xfer += $input->readStructEnd();
  return $xfer;
}

sub write {
  my ($self, $output) = @_;
  my $xfer   = 0;
  $xfer += $output->writeStructBegin('HandleData_add_entity_result');
  if (defined $self->{success}) {
    $xfer += $output->writeFieldBegin('success', TType::STRING, 0);
    $xfer += $output->writeString($self->{success});
    $xfer += $output->writeFieldEnd();
  }
  $xfer += $output->writeFieldStop();
  $xfer += $output->writeStructEnd();
  return $xfer;
}

package rs::thrift::HandleData_add_activity_args;
use base qw(Class::Accessor);
rs::thrift::HandleData_add_activity_args->mk_accessors( qw( activityJson ) );

sub new {
  my $classname = shift;
  my $self      = {};
  my $vals      = shift || {};
  $self->{activityJson} = undef;
  if (UNIVERSAL::isa($vals,'HASH')) {
    if (defined $vals->{activityJson}) {
      $self->{activityJson} = $vals->{activityJson};
    }
  }
  return bless ($self, $classname);
}

sub getName {
  return 'HandleData_add_activity_args';
}

sub read {
  my ($self, $input) = @_;
  my $xfer  = 0;
  my $fname;
  my $ftype = 0;
  my $fid   = 0;
  $xfer += $input->readStructBegin(\$fname);
  while (1) 
  {
    $xfer += $input->readFieldBegin(\$fname, \$ftype, \$fid);
    if ($ftype == TType::STOP) {
      last;
    }
    SWITCH: for($fid)
    {
      /^1$/ && do{      if ($ftype == TType::STRING) {
        $xfer += $input->readString(\$self->{activityJson});
      } else {
        $xfer += $input->skip($ftype);
      }
      last; };
        $xfer += $input->skip($ftype);
    }
    $xfer += $input->readFieldEnd();
  }
  $xfer += $input->readStructEnd();
  return $xfer;
}

sub write {
  my ($self, $output) = @_;
  my $xfer   = 0;
  $xfer += $output->writeStructBegin('HandleData_add_activity_args');
  if (defined $self->{activityJson}) {
    $xfer += $output->writeFieldBegin('activityJson', TType::STRING, 1);
    $xfer += $output->writeString($self->{activityJson});
    $xfer += $output->writeFieldEnd();
  }
  $xfer += $output->writeFieldStop();
  $xfer += $output->writeStructEnd();
  return $xfer;
}

package rs::thrift::HandleData_add_activity_result;
use base qw(Class::Accessor);
rs::thrift::HandleData_add_activity_result->mk_accessors( qw( success ) );

sub new {
  my $classname = shift;
  my $self      = {};
  my $vals      = shift || {};
  $self->{success} = undef;
  if (UNIVERSAL::isa($vals,'HASH')) {
    if (defined $vals->{success}) {
      $self->{success} = $vals->{success};
    }
  }
  return bless ($self, $classname);
}

sub getName {
  return 'HandleData_add_activity_result';
}

sub read {
  my ($self, $input) = @_;
  my $xfer  = 0;
  my $fname;
  my $ftype = 0;
  my $fid   = 0;
  $xfer += $input->readStructBegin(\$fname);
  while (1) 
  {
    $xfer += $input->readFieldBegin(\$fname, \$ftype, \$fid);
    if ($ftype == TType::STOP) {
      last;
    }
    SWITCH: for($fid)
    {
      /^0$/ && do{      if ($ftype == TType::STRING) {
        $xfer += $input->readString(\$self->{success});
      } else {
        $xfer += $input->skip($ftype);
      }
      last; };
        $xfer += $input->skip($ftype);
    }
    $xfer += $input->readFieldEnd();
  }
  $xfer += $input->readStructEnd();
  return $xfer;
}

sub write {
  my ($self, $output) = @_;
  my $xfer   = 0;
  $xfer += $output->writeStructBegin('HandleData_add_activity_result');
  if (defined $self->{success}) {
    $xfer += $output->writeFieldBegin('success', TType::STRING, 0);
    $xfer += $output->writeString($self->{success});
    $xfer += $output->writeFieldEnd();
  }
  $xfer += $output->writeFieldStop();
  $xfer += $output->writeStructEnd();
  return $xfer;
}

package rs::thrift::HandleDataIf;

use strict;


sub import_entities{
  my $self = shift;
  my $entityJson = shift;

  die 'implement interface';
}

sub add_entity{
  my $self = shift;
  my $entityJson = shift;

  die 'implement interface';
}

sub add_activity{
  my $self = shift;
  my $activityJson = shift;

  die 'implement interface';
}

package rs::thrift::HandleDataRest;

use strict;


sub new {
  my ($classname, $impl) = @_;
  my $self     ={ impl => $impl };

  return bless($self,$classname);
}

sub import_entities{
  my ($self, $request) = @_;

  my $entityJson = ($request->{'entityJson'}) ? $request->{'entityJson'} : undef;
  return $self->{impl}->import_entities($entityJson);
}

sub add_entity{
  my ($self, $request) = @_;

  my $entityJson = ($request->{'entityJson'}) ? $request->{'entityJson'} : undef;
  return $self->{impl}->add_entity($entityJson);
}

sub add_activity{
  my ($self, $request) = @_;

  my $activityJson = ($request->{'activityJson'}) ? $request->{'activityJson'} : undef;
  return $self->{impl}->add_activity($activityJson);
}

package rs::thrift::HandleDataClient;


use base qw(rs::thrift::HandleDataIf);
sub new {
  my ($classname, $input, $output) = @_;
  my $self      = {};
  $self->{input}  = $input;
  $self->{output} = defined $output ? $output : $input;
  $self->{seqid}  = 0;
  return bless($self,$classname);
}

sub import_entities{
  my $self = shift;
  my $entityJson = shift;

    $self->send_import_entities($entityJson);
  return $self->recv_import_entities();
}

sub send_import_entities{
  my $self = shift;
  my $entityJson = shift;

  $self->{output}->writeMessageBegin('import_entities', TMessageType::CALL, $self->{seqid});
  my $args = new rs::thrift::HandleData_import_entities_args();
  $args->{entityJson} = $entityJson;
  $args->write($self->{output});
  $self->{output}->writeMessageEnd();
  $self->{output}->getTransport()->flush();
}

sub recv_import_entities{
  my $self = shift;

  my $rseqid = 0;
  my $fname;
  my $mtype = 0;

  $self->{input}->readMessageBegin(\$fname, \$mtype, \$rseqid);
  if ($mtype == TMessageType::EXCEPTION) {
    my $x = new TApplicationException();
    $x->read($self->{input});
    $self->{input}->readMessageEnd();
    die $x;
  }
  my $result = new rs::thrift::HandleData_import_entities_result();
  $result->read($self->{input});
  $self->{input}->readMessageEnd();

  if (defined $result->{success} ) {
    return $result->{success};
  }
  die "import_entities failed: unknown result";
}
sub add_entity{
  my $self = shift;
  my $entityJson = shift;

    $self->send_add_entity($entityJson);
  return $self->recv_add_entity();
}

sub send_add_entity{
  my $self = shift;
  my $entityJson = shift;

  $self->{output}->writeMessageBegin('add_entity', TMessageType::CALL, $self->{seqid});
  my $args = new rs::thrift::HandleData_add_entity_args();
  $args->{entityJson} = $entityJson;
  $args->write($self->{output});
  $self->{output}->writeMessageEnd();
  $self->{output}->getTransport()->flush();
}

sub recv_add_entity{
  my $self = shift;

  my $rseqid = 0;
  my $fname;
  my $mtype = 0;

  $self->{input}->readMessageBegin(\$fname, \$mtype, \$rseqid);
  if ($mtype == TMessageType::EXCEPTION) {
    my $x = new TApplicationException();
    $x->read($self->{input});
    $self->{input}->readMessageEnd();
    die $x;
  }
  my $result = new rs::thrift::HandleData_add_entity_result();
  $result->read($self->{input});
  $self->{input}->readMessageEnd();

  if (defined $result->{success} ) {
    return $result->{success};
  }
  die "add_entity failed: unknown result";
}
sub add_activity{
  my $self = shift;
  my $activityJson = shift;

    $self->send_add_activity($activityJson);
  return $self->recv_add_activity();
}

sub send_add_activity{
  my $self = shift;
  my $activityJson = shift;

  $self->{output}->writeMessageBegin('add_activity', TMessageType::CALL, $self->{seqid});
  my $args = new rs::thrift::HandleData_add_activity_args();
  $args->{activityJson} = $activityJson;
  $args->write($self->{output});
  $self->{output}->writeMessageEnd();
  $self->{output}->getTransport()->flush();
}

sub recv_add_activity{
  my $self = shift;

  my $rseqid = 0;
  my $fname;
  my $mtype = 0;

  $self->{input}->readMessageBegin(\$fname, \$mtype, \$rseqid);
  if ($mtype == TMessageType::EXCEPTION) {
    my $x = new TApplicationException();
    $x->read($self->{input});
    $self->{input}->readMessageEnd();
    die $x;
  }
  my $result = new rs::thrift::HandleData_add_activity_result();
  $result->read($self->{input});
  $self->{input}->readMessageEnd();

  if (defined $result->{success} ) {
    return $result->{success};
  }
  die "add_activity failed: unknown result";
}
package rs::thrift::HandleDataProcessor;

use strict;


sub new {
    my ($classname, $handler) = @_;
    my $self      = {};
    $self->{handler} = $handler;
    return bless ($self, $classname);
}

sub process {
    my ($self, $input, $output) = @_;
    my $rseqid = 0;
    my $fname  = undef;
    my $mtype  = 0;

    $input->readMessageBegin(\$fname, \$mtype, \$rseqid);
    my $methodname = 'process_'.$fname;
    if (!$self->can($methodname)) {
      $input->skip(TType::STRUCT);
      $input->readMessageEnd();
      my $x = new TApplicationException('Function '.$fname.' not implemented.', TApplicationException::UNKNOWN_METHOD);
      $output->writeMessageBegin($fname, TMessageType::EXCEPTION, $rseqid);
      $x->write($output);
      $output->writeMessageEnd();
      $output->getTransport()->flush();
      return;
    }
    $self->$methodname($rseqid, $input, $output);
    return 1;
}

sub process_import_entities {
    my ($self, $seqid, $input, $output) = @_;
    my $args = new rs::thrift::HandleData_import_entities_args();
    $args->read($input);
    $input->readMessageEnd();
    my $result = new rs::thrift::HandleData_import_entities_result();
    $result->{success} = $self->{handler}->import_entities($args->entityJson);
    $output->writeMessageBegin('import_entities', TMessageType::REPLY, $seqid);
    $result->write($output);
    $output->writeMessageEnd();
    $output->getTransport()->flush();
}

sub process_add_entity {
    my ($self, $seqid, $input, $output) = @_;
    my $args = new rs::thrift::HandleData_add_entity_args();
    $args->read($input);
    $input->readMessageEnd();
    my $result = new rs::thrift::HandleData_add_entity_result();
    $result->{success} = $self->{handler}->add_entity($args->entityJson);
    $output->writeMessageBegin('add_entity', TMessageType::REPLY, $seqid);
    $result->write($output);
    $output->writeMessageEnd();
    $output->getTransport()->flush();
}

sub process_add_activity {
    my ($self, $seqid, $input, $output) = @_;
    my $args = new rs::thrift::HandleData_add_activity_args();
    $args->read($input);
    $input->readMessageEnd();
    my $result = new rs::thrift::HandleData_add_activity_result();
    $result->{success} = $self->{handler}->add_activity($args->activityJson);
    $output->writeMessageBegin('add_activity', TMessageType::REPLY, $seqid);
    $result->write($output);
    $output->writeMessageEnd();
    $output->getTransport()->flush();
}

1;
