/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "data_constants.h"

namespace recsys {

const dataConstants g_data_constants;

dataConstants::dataConstants() {
}

} // namespace

